# Generated by Django 5.1.7 on 2025-03-21 03:31

import datetime
import django.db.models.deletion
import goose_farmer_game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goose_farmer_game', '0002_alter_verificationtoken_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='verificationtokens', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 21, 13, 31, 5, 171057, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='key',
            field=models.CharField(default=goose_farmer_game.models.Token.random_string, primary_key=True, serialize=False),
        ),
    ]
