# Generated by Django 5.1.7 on 2025-03-22 17:31

import datetime
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('goose_farmer_game', '0004_alter_verificationtoken_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('species', models.TextField()),
                ('icon', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_weight_male', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_weight_female', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('coop_level', models.IntegerField(default=1)),
                ('summons', models.IntegerField(default=0)),
                ('feed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 23, 3, 31, 17, 547923, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.CharField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('base_color', models.CharField()),
                ('extra_color', models.CharField(blank=True, null=True)),
                ('rarity', models.CharField(choices=[('COMMON', 'common'), ('RARE', 'rare'), ('EPIC', 'epic'), ('LEGENDARY', 'legendary')])),
                ('bird_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birds', to='goose_farmer_game.birdtype')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds', to='goose_farmer_game.player')),
            ],
        ),
    ]
