# Generated by Django 5.1.7 on 2025-03-22 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goose_farmer_game', '0006_alter_verificationtoken_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdtype',
            name='max_weight_male',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birdtype',
            name='min_weight_female',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 23, 3, 55, 21, 597975, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
