# Generated by Django 5.1.7 on 2025-03-23 18:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goose_farmer_game', '0007_birdtype_max_weight_male_birdtype_min_weight_female_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birdtype',
            old_name='max_weight_female',
            new_name='max_weight',
        ),
        migrations.RenameField(
            model_name='birdtype',
            old_name='max_weight_male',
            new_name='min_weight',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='money',
            new_name='eggs',
        ),
        migrations.RemoveField(
            model_name='birdtype',
            name='min_weight_female',
        ),
        migrations.RemoveField(
            model_name='birdtype',
            name='min_weight_male',
        ),
        migrations.AddField(
            model_name='bird',
            name='assigned_to_coop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bird',
            name='beak_color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='egg_timer',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='bird',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bird',
            name='eye_color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='health',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='bird',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='leg_color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bird',
            name='stars',
            field=models.CharField(default=3),
        ),
        migrations.AddField(
            model_name='birdtype',
            name='egg_timer',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 24, 4, 24, 19, 822400, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='DropWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_color', models.CharField()),
                ('extra_color', models.CharField(blank=True, null=True)),
                ('beak_color', models.CharField(blank=True, null=True)),
                ('leg_color', models.CharField(blank=True, null=True)),
                ('eye_color', models.CharField(blank=True, null=True)),
                ('rarity', models.CharField(choices=[('COMMON', 'common'), ('RARE', 'rare'), ('EPIC', 'epic'), ('LEGENDARY', 'legendary')])),
                ('drop_weight', models.IntegerField(default=1)),
                ('bird_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_weights', to='goose_farmer_game.birdtype')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('exp_reward', models.PositiveBigIntegerField(default=0)),
                ('egg_reward', models.PositiveBigIntegerField(default=0)),
                ('feed_reward', models.PositiveBigIntegerField(default=0)),
                ('summon_reward', models.PositiveBigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='goose_farmer_game.player')),
            ],
        ),
        migrations.CreateModel(
            name='MissionObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.CharField()),
                ('progress', models.PositiveIntegerField(default=0)),
                ('target', models.PositiveIntegerField(default=1)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='goose_farmer_game.mission')),
            ],
        ),
    ]
