# Generated by Django 5.1.7 on 2025-03-24 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goose_farmer_game', '0009_alter_player_options_alter_player_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 25, 0, 27, 50, 628104, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
