# Generated by Django 5.1.7 on 2025-04-06 21:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goose_farmer_game', '0011_alter_bird_level_alter_player_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='eggs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 7, 7, 5, 1, 471344, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
