# Generated by Django 5.1.7 on 2025-04-07 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goose_farmer_game', '0012_alter_player_eggs_alter_verificationtoken_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='repeat',
            field=models.CharField(choices=[('NONE', 'none'), ('DAILY', 'daily'), ('WEEKLY', 'weekly'), ('MONTHLY', 'monthly')], default='NONE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 7, 10, 52, 36, 910231, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
