# Generated by Django 5.1.7 on 2025-04-07 06:05

import datetime
import django.db.models.deletion
import goose_farmer_game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goose_farmer_game', '0013_mission_repeat_alter_verificationtoken_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 7, 16, 5, 5, 292205, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuestVerificationToken',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 7, 16, 5, 5, 292205, tzinfo=datetime.timezone.utc), null=True)),
                ('key', models.CharField(default=goose_farmer_game.models.Token.random_string, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
