# Generated by Django 5.1.7 on 2025-04-07 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goose_farmer_game', '0014_alter_verificationtoken_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guestverificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 7, 17, 10, 43, 538346, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 7, 17, 10, 43, 538346, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
